from os import PathLike
from typing import Iterable, Sequence

ReadableBuffer = bytes | bytearray | memoryview
PathInput = str | PathLike[str]

class PariError(Exception): ...
class ConfigurationError(PariError): ...
class CompatibilityError(PariError): ...
class DuplicateKeyError(PariError): ...
class StorageError(PariError): ...
class ClosedIndexError(PariError): ...

class MinHash:
    def __init__(self, num_perm: int = 128, seed: int = 1) -> None: ...
    @staticmethod
    def from_values(
        values: Iterable[ReadableBuffer], *, num_perm: int = 128, seed: int = 1
    ) -> MinHash: ...
    def update(self, value: ReadableBuffer) -> None: ...
    def update_many(self, values: Iterable[ReadableBuffer]) -> None: ...
    def jaccard(self, other: MinHash) -> float: ...
    def merge(self, other: MinHash) -> None: ...
    def clear(self) -> None: ...
    @property
    def seed(self) -> int: ...
    @property
    def num_perm(self) -> int: ...
    @property
    def scheme(self) -> str: ...
    @property
    def signature(self) -> list[int]: ...
    @property
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class IndexStats:
    @property
    def items(self) -> int: ...
    @property
    def file_bytes(self) -> int: ...
    @property
    def dirty(self) -> bool: ...
    @property
    def bands(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def committed_buckets(self) -> int: ...
    @property
    def overlay_buckets(self) -> int: ...
    @property
    def suppressed_base_keys(self) -> int: ...

class Index:
    @staticmethod
    def create(
        path: PathInput,
        *,
        threshold: float = 0.8,
        num_perm: int = 128,
        seed: int = 1,
    ) -> Index: ...
    @staticmethod
    def open(path: PathInput) -> Index: ...
    def add(self, key: int, sketch: MinHash) -> None: ...
    def add_many(self, items: Sequence[tuple[int, MinHash]]) -> None: ...
    def search(self, sketch: MinHash) -> list[int]: ...
    def search_many(self, sketches: Sequence[MinHash]) -> list[list[int]]: ...
    def remove(self, key: int) -> bool: ...
    def contains(self, key: int) -> bool: ...
    def stats(self) -> IndexStats: ...
    def flush(self) -> None: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: int) -> bool: ...
    def __enter__(self) -> Index: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...

__version__: str
