from collections.abc import Callable, Iterable, Sequence
from os import PathLike
from typing import Generic, Literal, TypeAlias, TypeVar

ReadableBuffer: TypeAlias = bytes | bytearray | memoryview
PathInput: TypeAlias = str | PathLike[str]
_T = TypeVar("_T")
_FeatureExtractor: TypeAlias = Callable[[_T], Iterable[ReadableBuffer]]
_ExactVerifier: TypeAlias = Callable[[_T, _T], bool]
_RepresentativeSelector: TypeAlias = Callable[[Sequence[_T]], _T]
_Backend: TypeAlias = Literal["memory", "local"]

class PariError(Exception): ...
class ConfigurationError(PariError): ...
class CompatibilityError(PariError): ...
class DuplicateKeyError(PariError): ...
class StorageError(PariError): ...
class ClosedIndexError(PariError): ...
class DedupeError(PariError): ...
class InvalidRepresentativeError(DedupeError): ...
class ProgressCancelledError(DedupeError):
    completed: int

class ProgressEvent:
    phase: Literal["dedupe_index"]
    completed: int
    total: int | None
    batch_size: int
    elapsed_seconds: float
    items_per_second: float
    final: bool

class DuplicateGroup(Generic[_T]):
    representative: _T
    members: tuple[_T, ...]
    representative_index: int
    member_indices: tuple[int, ...]

class DeduplicationResult(Generic[_T]):
    groups: tuple[DuplicateGroup[_T], ...]
    kept: tuple[_T, ...]
    dropped: tuple[_T, ...]
    kept_indices: tuple[int, ...]
    dropped_indices: tuple[int, ...]
    @property
    def group_count(self) -> int: ...
    @property
    def duplicate_count(self) -> int: ...

class MinHash:
    def __init__(self, num_perm: int = 128, seed: int = 1) -> None: ...
    @staticmethod
    def from_values(
        values: Iterable[ReadableBuffer], *, num_perm: int = 128, seed: int = 1
    ) -> MinHash: ...
    @staticmethod
    def from_batch(
        rows: Iterable[Iterable[ReadableBuffer]],
        *,
        num_perm: int = 128,
        seed: int = 1,
        threads: int | None = None,
    ) -> list[MinHash]: ...
    @staticmethod
    def from_signature(signature: Iterable[int], *, seed: int = 1) -> MinHash: ...
    def update(self, value: ReadableBuffer) -> None: ...
    def update_many(self, values: Iterable[ReadableBuffer]) -> None: ...
    def jaccard(self, other: MinHash) -> float: ...
    def merge(self, other: MinHash) -> None: ...
    def clear(self) -> None: ...
    @property
    def seed(self) -> int: ...
    @property
    def num_perm(self) -> int: ...
    @property
    def scheme(self) -> str: ...
    @property
    def signature(self) -> list[int]: ...
    @property
    def permutations(self) -> tuple[list[int], list[int]]: ...
    @property
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

class IndexStats:
    @property
    def items(self) -> int: ...
    @property
    def file_bytes(self) -> int: ...
    @property
    def dirty(self) -> bool: ...
    @property
    def bands(self) -> int: ...
    @property
    def rows(self) -> int: ...
    @property
    def committed_buckets(self) -> int: ...
    @property
    def overlay_buckets(self) -> int: ...
    @property
    def suppressed_base_keys(self) -> int: ...
    @property
    def committed_memberships(self) -> int: ...
    @property
    def committed_bucket_minimum(self) -> int: ...
    @property
    def committed_bucket_p50(self) -> int: ...
    @property
    def committed_bucket_p95(self) -> int: ...
    @property
    def committed_bucket_p99(self) -> int: ...
    @property
    def committed_bucket_maximum(self) -> int: ...
    @property
    def committed_bucket_average(self) -> float: ...
    @property
    def overlay_memberships(self) -> int: ...
    @property
    def query_operations(self) -> int | None: ...
    @property
    def query_count(self) -> int | None: ...
    @property
    def candidate_count(self) -> int | None: ...
    @property
    def candidate_rate(self) -> float | None: ...
    @property
    def average_query_ms(self) -> float | None: ...
    @property
    def max_query_ms(self) -> float | None: ...

class Index:
    @staticmethod
    def create(
        path: PathInput,
        *,
        threshold: float = 0.8,
        num_perm: int = 128,
        seed: int = 1,
        observability: bool = False,
    ) -> Index: ...
    @staticmethod
    def open(path: PathInput, *, observability: bool = False) -> Index: ...
    def add(self, key: int, sketch: MinHash) -> None: ...
    def add_many(self, items: Sequence[tuple[int, MinHash]]) -> None: ...
    def search(self, sketch: MinHash) -> list[int]: ...
    def search_many(self, sketches: Sequence[MinHash]) -> list[list[int]]: ...
    def remove(self, key: int) -> bool: ...
    def contains(self, key: int) -> bool: ...
    def stats(self) -> IndexStats: ...
    def set_observability(self, enabled: bool = True) -> None: ...
    def flush(self) -> None: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: int) -> bool: ...
    def __enter__(self) -> Index: ...
    def __exit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> bool: ...

class DedupeIndex(Generic[_T]):
    threshold: float
    num_perm: int
    seed: int
    threads: int | None
    backend: _Backend
    def __init__(
        self,
        feature: _FeatureExtractor[_T] | None = None,
        *,
        threshold: float = 0.8,
        num_perm: int = 128,
        seed: int = 1,
        batch_size: int = 1024,
        threads: int | None = None,
        path: PathInput | None = None,
        backend: _Backend | None = None,
        exact: _ExactVerifier[_T] | None = None,
        representative: _RepresentativeSelector[_T] | None = None,
    ) -> None: ...
    @property
    def batch_size(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    def add(self, record: _T) -> int: ...
    def add_many(
        self,
        records: Iterable[_T],
        *,
        progress: Callable[[ProgressEvent], bool | None] | None = None,
    ) -> int: ...
    def add_features(self, record: _T, features: Iterable[ReadableBuffer]) -> int: ...
    def add_many_features(
        self,
        items: Iterable[tuple[_T, Iterable[ReadableBuffer]]],
        *,
        progress: Callable[[ProgressEvent], bool | None] | None = None,
    ) -> int: ...
    def candidate_groups(self) -> tuple[DuplicateGroup[_T], ...]: ...
    def groups(self) -> tuple[DuplicateGroup[_T], ...]: ...
    def result(self) -> DeduplicationResult[_T]: ...
    def sync(self) -> None: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> DedupeIndex[_T]: ...
    def __exit__(
        self, exc_type: object, exc_value: object, traceback: object
    ) -> Literal[False]: ...

def deduplicate(
    records: Iterable[_T],
    *,
    feature: _FeatureExtractor[_T],
    threshold: float = 0.8,
    num_perm: int = 128,
    seed: int = 1,
    batch_size: int = 1024,
    threads: int | None = None,
    path: PathInput | None = None,
    backend: _Backend | None = None,
    exact: _ExactVerifier[_T] | None = None,
    representative: _RepresentativeSelector[_T] | None = None,
    progress: Callable[[ProgressEvent], bool | None] | None = None,
) -> DeduplicationResult[_T]: ...

__version__: str
