[package]
name = "pari-store"
description = "Crash-safe local persistent similarity indexes for the Pari engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pari-core = { version = "=0.2.0", path = "../pari-core" }
pari-format = { version = "=0.2.0", path = "../pari-format" }
pari-index = { version = "=0.2.0", path = "../pari-index" }
same-file = "1.0.6"

[lints]
workspace = true
