[package]
name = "pari-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pari-core = { path = "../pari-core" }
pari-format = { path = "../pari-format" }
pari-index = { path = "../pari-index" }

[lints]
workspace = true
