[package]
name = "pari-store-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
crc32fast = "1.5"
pari-format = { path = "../pari-format" }
same-file = "1.0.6"

[dev-dependencies]
pari-core = { path = "../pari-core" }
pari-store = { path = "../pari-store" }
pari-store-lazy = { path = "../pari-store-lazy" }

[lints]
workspace = true
